Feature/task 1 shoe factory
SaraiNina/Object-modelling pull request #2
Opened 2023-01-02 11:23 UTC by SaraiNina

Am facut push de pe local pe remote, apoi am facut pull reguest pe master

2023-01-03 16:26 UTC, alexandru-corghencea requested changes

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/KidsShoe.java
> +package com.nina.modelling.shoes;
Please rename pull request to respect format task name and some general meaningful name. for example: [TASK-1] Shoe Object Modelling

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/KidsShoe.java
> +public class KidsShoe extends Shoe {
KidShoe

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/KidsShoe.java
> +    public String getCategory(){
In this case better remove word get from method names

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/Shoe.java
> +public  Shoe(int size){
Format code folding style for whole classes. Code->Reformat Code

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/ShoeFactory.java
> +        KidsShoe kidsShoe = new KidsShoe("Summer");
We need to create objects for each type of constructor and try to instantiate all fields defined in classes.

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/ShoeFactory.java
> +        MenShoe menShoe1 = new MenShoe();
Bad practice to name variables Student1 and Strudent2, please rename to studentAna and studentIon or just ana and ion.

2023-01-03 16:26 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/ShoeFactory.java
> +public class ShoeFactory extends Shoe {
Please read clean code rules and apply: https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29

2023-01-04 17:28 UTC, alexandru-corghencea requested changes

2023-01-04 17:28 UTC, alexandru-corghencea commented on src/main/java/com/nina/modelling/shoes/KidsShoe.java
>  public class KidsShoe extends Shoe {
All class names and variables, comments, commits, branches and even github comments should be in English.

2023-01-10 13:23 UTC, alexandru-corghencea requested changes

2023-01-10 13:23 UTC, alexandru-corghencea commented on src/main/java/com/nina/modelling/shoes/MenShoe.java
>  public class MenShoe extends Shoe {
ManShoe

2023-01-10 18:49 UTC, alexandru-corghencea requested changes

2023-01-10 18:49 UTC, alexandru-corghencea commented on Task 1 - Shoe Object Modelling.txt
> +Object Modeling Shoes:
Move the file into resource folder
https://stackoverflow.com/questions/25786185/what-is-the-purpose-for-the-resource-folder-in-maven

2023-01-11 08:29 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/KidsShoe.java
> +package com.nina.modelling.shoes;
test

2023-01-11 08:33 UTC, SaraiNina commented
SAL

2023-01-11 16:16 UTC, SaraiNina reviewed
Changes executed

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/KidsShoe.java
> +package com.nina.modelling.shoes;
I rename pull request in english.

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/KidsShoe.java
> +public class KidsShoe extends Shoe {
I changed name of class KidShoe

2023-01-11 16:16 UTC, SaraiNina commented on src/main/java/com/nina/modelling/shoes/KidsShoe.java
>  public class KidsShoe extends Shoe {
Ok

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/KidsShoe.java
> +    public String getCategory(){
I change the name of methods in class KidShoe

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/ShoeFactory.java
> +        KidsShoe kidsShoe = new KidsShoe("Summer");
I created objects for each type of constructors and instantiated it.

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/ShoeFactory.java
> +        MenShoe menShoe1 = new MenShoe();
I know

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/Shoe.java
> +public  Shoe(int size){
I format cod for  all classes

2023-01-11 16:16 UTC, SaraiNina commented on com/nina/modelling/shoes/ShoeFactory.java
> +public class ShoeFactory extends Shoe {
I read about clean code

2023-01-11 16:16 UTC, SaraiNina commented on src/main/java/com/nina/modelling/shoes/MenShoe.java
>  public class MenShoe extends Shoe {
Written a correct name

2023-01-11 16:16 UTC, SaraiNina commented on Task 1 - Shoe Object Modelling.txt
> +Object Modeling Shoes:
A resource folder was added .

2023-01-12 07:40 UTC, alexandru-corghencea requested changes

2023-01-12 07:40 UTC, alexandru-corghencea commented on src/main/java/com/nina/modelling/shoes/ShoeFactory.java
>          WomanShoe womanShoe1 = new WomanShoe("Flower", "Zar");
No variables of womanShoe 1,2,3
needs better name

2023-01-12 07:40 UTC, alexandru-corghencea commented on src/main/java/com/nina/modelling/shoes/KidShoe.java
> +    public String Type() {
If you changed these getters to naming without get, make this change for all getters in the code.

2023-01-12 07:40 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/ShoeFactory.java
> +        MenShoe menShoe1 = new MenShoe();
So change it please

2023-01-12 07:40 UTC, alexandru-corghencea requested changes

2023-01-12 07:40 UTC, alexandru-corghencea commented on com/nina/modelling/shoes/MenShoe.java
> +public class MenShoe extends Shoe {
Objects should be in singular mode

2023-01-12 14:15 UTC, alexandru-corghencea requested changes
All commit messages, objects and filenames should respect the format and language

2023-01-12 14:26 UTC, alexandru-corghencea requested changes

2023-01-12 14:26 UTC, alexandru-corghencea commented on src/main/java/com/nina/modelling/shoes/KidShoe.java
>          return accessory;
All commit messages, objects and filenames should respect the format and language

2023-01-13 11:12 UTC, alexandru-corghencea requested changes

2023-01-13 11:12 UTC, alexandru-corghencea commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
test comment thread

2023-01-13 11:20 UTC, closed without merging